### ISSUE TITLE
The kernel appears to have died. It will restart automatically

### ISSUE THREAD

**Issue by nabetse00** [gitcoinco/gitcoin_cadcad_model#2]
I extracted the file, corrected some deps on anaconda (cadCAD required numpy == 1.18.1), restarted and rerun.
The jupyter notebook kernel keeps on "The kernel appears to have died. It will restart automatically." on 
```
df = result.loc[(0, 0, 1, slice(None))]
```
My laptop only has 8 Go of ram, maybe that is the problem.

**Comment by nabetse00** [comment]
@danlessa answered:
Insufficient RAM certainly can kill the kernel. The most straightforward way to you to be able to play with the data would be to re-run the simulation with only the first 500 events. Change the line for it on `env_params.py` file and run the simulation so that you have a leaner data file

**Comment by nabetse00** [comment]
Indeed the solution is:
- decompress simulation_result.tar.xz to simulation_result.pkl.gz
- change env_config.py -> os.environ['GITCOIN_TIMESTEPS'] = str(6000) to something less. (in my case  str(500) works)
- Rerun 'python run_simulation.py' in your conda env (in my case i needed to restart powershell terminal and rerun)

This is a abstract of a conversation over email with @danlessa in order to help others to overcome this issue.

Thanks again @danlessa for the support !

**Comment by danlessa** [comment]
Thanks @nabetse00 for sharing the issue and the conversation! Happy to help whenever you have any additional question ;)
